apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-number-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-number-app
  template:
    metadata:
      labels:
        app: random-number-app
    spec:
      containers:
      - name: random-number-container
        image: darkkuroe/random-number-app:latest
        command: ["python", "random_number.py"]
